---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: centos-6.4

suites:
  - name: default
    run_list:
      - recipe[hrforecast::default]
    attributes:
      mysql:
        server_debian_password: test
        server_repl_password: test
        server_root_password: test
